services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    volumes:
      - .:/app
    ports:
      - ${PORT}:${PORT}
    expose:
      - ${PORT}